- name: UFW - Install
  ansible.builtin.apt:
    name: ufw
    state: present

- name: UFW - HTTP and HTTPS
  community.general.ufw:
    rule: allow
    port: '{{ item[0] }}'
    proto: tcp
    src: '{{ item[1] }}'
  loop: "{{ ['80', '443'] | product(tjo_space_networks) | list }}"

- name: UFW - Allow SSH
  community.general.ufw:
    rule: allow
    port: '2222'
    proto: tcp

- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny
